const socials=[
['Spotify','https://open.spotify.com/artist/0OTAJtLNsE17IL2Bdru0Wf'],['YouTube','https://www.youtube.com/@GrimeyGoons'],['Facebook','https://www.facebook.com/profile.php?id=61568609348416'],['GG Music Facebook','https://www.facebook.com/profile.php?id=61568327327049'],['TikTok','https://tiktok.com/@grimeygoons'],['Threads','https://threads.net/grimey_goons'],['Bluesky','https://bsky.app/profile/grimeygoons.link'],['Twitch','https://twitch.tv/grimey_goons'],['Vimeo','https://vimeo.com/user233536758'],['Reddit','https://www.reddit.com/user/Grimey_Goons'],['Tumblr','https://grimeygoons.tumblr.com'],['Pinterest','https://www.pinterest.com/grimeygoons'],['X','https://x.com/GrimeyGoonsGG'],['Flickr','https://www.flickr.com/people/203387969@N07'],['Mastodon','https://mastodon.social/@Grimeygoons'],['LinkedIn','https://www.linkedin.com/in/grimey-goons-757266346'],['GitHub','https://github.com/Grimeygoons'],['Goodreads','https://www.goodreads.com/grimeygoons'],['Fediverse / Link Hub','https://grimeygoons.link'],['Patreon','https://www.patreon.com/GrimeyGoons'],['PayPal','https://www.paypal.me/grimeygoonsllc'],['eBay','https://www.ebay.com/usr/gri_7225'],['GitLab','https://gitlab.com/grimeygoonsrecording'],['Strava','https://www.strava.com/athletes/ggoons'],['Calendly','https://calendly.com/grimeygoonsrecording'],['TripIt','https://tripit.com/people/grimeygoonsrecording'],['Foursquare','https://foursquare.com/user/1411914245'],['Stack Overflow','https://stackoverflow.com/users/29165758/grimey-goons'],['Dribbble','https://dribbble.com/grimey-goons'],['ORCID','https://orcid.org/0009-0005-5698-2482']];
const sg=document.getElementById('socialGrid');socials.forEach(([n,u])=>{const a=document.createElement('a');a.className='social-card';a.href=u;a.target='_blank';a.rel='noopener';a.innerHTML=`<strong>${n}</strong><span>↗</span>`;sg.appendChild(a)});
document.getElementById('year').textContent=new Date().getFullYear();const nav=document.querySelector('.site-header nav');document.querySelector('.menu-toggle').onclick=()=>nav.classList.toggle('open');nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));window.addEventListener('scroll',()=>{const h=document.documentElement;document.getElementById('scrollProgress').style.width=(h.scrollTop/(h.scrollHeight-h.clientHeight)*100)+'%'});
// YouTube's public RSS feed means new public uploads can appear here without editing this site.
const CHANNEL='UCJcPOEJfIM39gw10CJKAm8w', feed=document.getElementById('youtubeFeed');
async function loadYouTube(){try{const rss=`https://www.youtube.com/feeds/videos.xml?channel_id=${CHANNEL}`;const proxy=`https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(rss)}`;const r=await fetch(proxy);if(!r.ok)throw Error();const d=await r.json();if(!d.items?.length)throw Error();feed.innerHTML='';d.items.slice(0,6).forEach(v=>{const id=(v.guid||'').split(':').pop();const a=document.createElement('a');a.className='video-card';a.href=v.link;a.target='_blank';a.rel='noopener';a.innerHTML=`<img loading="lazy" src="https://i.ytimg.com/vi/${id}/hqdefault.jpg" alt=""><div><h3>${v.title}</h3></div>`;feed.appendChild(a)})}catch(e){feed.innerHTML='<div class="feed-loading">Latest videos could not be loaded here right now. Use the button below to view the live YouTube channel.</div>'}}loadYouTube();


// v4.2 navigation state, floating top control, and desktop custom cursor
const header=document.querySelector('.site-header'), backTop=document.getElementById('backToTop'), navLinks=[...document.querySelectorAll('.site-header nav a')];
navLinks.forEach(link=>link.addEventListener('click',()=>{header.classList.remove('nav-pulse');void header.offsetWidth;header.classList.add('nav-pulse');setTimeout(()=>header.classList.remove('nav-pulse'),360)}));
const sections=[...document.querySelectorAll('main section[id]')];
const setActiveNav=()=>{const y=window.scrollY+window.innerHeight*.3;let active=sections[0]?.id;sections.forEach(s=>{if(s.offsetTop<=y)active=s.id});navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+active));backTop.classList.toggle('show',window.scrollY>Math.max(520,window.innerHeight*.65))};
window.addEventListener('scroll',setActiveNav,{passive:true});setActiveNav();backTop.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
if(matchMedia('(pointer:fine)').matches){const glow=document.getElementById('cursorGlow'),dot=document.getElementById('cursorDot');let x=innerWidth/2,y=innerHeight/2,gx=x,gy=y;addEventListener('mousemove',e=>{x=e.clientX;y=e.clientY;dot.style.transform=`translate3d(${x}px,${y}px,0)`;document.body.classList.add('cursor-ready')},{passive:true});const tick=()=>{gx+=(x-gx)*.18;gy+=(y-gy)*.18;glow.style.transform=`translate3d(${gx}px,${gy}px,0)`;requestAnimationFrame(tick)};tick();document.querySelectorAll('a,button,.social-card,.video-card').forEach(el=>{el.addEventListener('mouseenter',()=>document.body.classList.add('cursor-hover'));el.addEventListener('mouseleave',()=>document.body.classList.remove('cursor-hover'))})}
